// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";
import {ReportVerifier} from "../src/ReportVerifier.sol";
import {RebalanceVault} from "../src/RebalanceVault.sol";
import {TreasuryPolicy} from "../src/TreasuryPolicy.sol";
import {MockAttestationVerifier} from "../src/mocks/MockAttestationVerifier.sol";
import {MockFxVenue} from "../src/mocks/MockFxVenue.sol";
import {MockPriceOracle} from "../src/mocks/MockPriceOracle.sol";
import {MockERC20} from "../src/mocks/MockERC20.sol";

/**
 * @title Conformance between the TypeScript engine and the contracts
 *
 * @dev The off-chain engine recomputes in TypeScript what Solidity computes here: ABI
 *      encoding, EIP-712 type hashes, the order commitment, the idempotency key. Two
 *      independent implementations of the same encoding, cross-checked on every test run.
 *
 *      Without this suite, a divergence — a comma in a type signature, a forgotten sign
 *      extension on a negative integer — would only show up when a perfectly valid report
 *      got rejected, with no clue as to why.
 *
 *      The fixture is generated by `node engine/scripts/fixtures.ts`.
 */
contract ConformanceTest is Test {
    string internal json;
    ReportVerifier internal verifier;
    RebalanceVault internal vault;

    function setUp() public {
        json = vm.readFile("test/fixtures/conformance.json");

        TreasuryPolicy policy = new TreasuryPolicy(address(this), 1 hours);
        verifier = new ReportVerifier(policy, new MockAttestationVerifier(), keccak256("m"));
        MockERC20 usdc = new MockERC20("USD Coin", "USDC");
        vault = new RebalanceVault(
            policy, verifier, address(usdc), new MockFxVenue(), new MockPriceOracle()
        );
    }

    function _orders() internal view returns (RebalanceVault.Order[] memory o) {
        o = new RebalanceVault.Order[](2);
        for (uint256 i = 0; i < 2; i++) {
            string memory base = string.concat(".orders[", vm.toString(i), "]");
            o[i] = RebalanceVault.Order({
                sell: vm.parseJsonAddress(json, string.concat(base, ".sell")),
                buy: vm.parseJsonAddress(json, string.concat(base, ".buy")),
                amountIn: uint128(vm.parseJsonUint(json, string.concat(base, ".amountIn"))),
                minAmountOut: uint128(vm.parseJsonUint(json, string.concat(base, ".minAmountOut")))
            });
        }
    }

    function _report() internal view returns (ReportVerifier.RebalanceReport memory r) {
        r = ReportVerifier.RebalanceReport({
            epoch: uint64(vm.parseJsonUint(json, ".report.epoch")),
            nonce: uint64(vm.parseJsonUint(json, ".report.nonce")),
            expiry: uint64(vm.parseJsonUint(json, ".report.expiry")),
            inputsTimestamp: uint64(vm.parseJsonUint(json, ".report.inputsTimestamp")),
            policyVersion: uint32(vm.parseJsonUint(json, ".report.policyVersion")),
            bandParamsHash: vm.parseJsonBytes32(json, ".report.bandParamsHash"),
            inputsHash: vm.parseJsonBytes32(json, ".report.inputsHash"),
            ordersCommitment: vm.parseJsonBytes32(json, ".report.ordersCommitment"),
            esBeforeBps: int32(vm.parseJsonInt(json, ".report.esBeforeBps")),
            esAfterBps: int32(vm.parseJsonInt(json, ".report.esAfterBps")),
            costEstimate: uint128(vm.parseJsonUint(json, ".report.costEstimate")),
            grossNotional: uint128(vm.parseJsonUint(json, ".report.grossNotional"))
        });
    }

    /// @dev The encoding of a dynamic array of static structs followed by a fixed word:
    ///      head offset, length, then four words per order.
    function test_ordersCommitmentMatchesTheEngine() public view {
        bytes32 expected = vm.parseJsonBytes32(json, ".ordersCommitment");
        bytes32 salt = vm.parseJsonBytes32(json, ".salt");
        assertEq(keccak256(abi.encode(_orders(), salt)), expected);
    }

    function test_reportTypeHashMatchesTheEngine() public view {
        bytes32 expected = vm.parseJsonBytes32(json, ".reportTypeHash");
        bytes32 actual = keccak256(
            "RebalanceReport(uint64 epoch,uint64 nonce,uint64 expiry,uint64 inputsTimestamp,"
            "uint32 policyVersion,bytes32 bandParamsHash,bytes32 inputsHash,"
            "bytes32 ordersCommitment,int32 esBeforeBps,int32 esAfterBps,uint128 costEstimate,"
            "uint128 grossNotional)"
        );
        assertEq(actual, expected);
    }

    function test_domainTypeHashMatchesTheEngine() public view {
        assertEq(
            keccak256(
                "EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)"
            ),
            vm.parseJsonBytes32(json, ".domainTypeHash")
        );
    }

    /**
     * @dev The fixture deliberately contains a **negative** metric: sign extension to
     *      256 bits is the easiest thing to get wrong on the TypeScript side, and its
     *      failure is perfectly silent — the encoding stays well formed, only the digest
     *      differs.
     */
    function test_reportStructHashMatchesTheEngine() public view {
        assertLt(vm.parseJsonInt(json, ".report.esAfterBps"), 0, "fixture must exercise a negative");
        assertEq(verifier.structHash(_report()), vm.parseJsonBytes32(json, ".reportStructHash"));
    }

    function test_reportIdMatchesTheEngine() public view {
        assertEq(verifier.reportId(_report()), vm.parseJsonBytes32(json, ".reportId"));
    }

    /**
     * @dev The Privy policies allow only a list of function selectors. A signature
     *      mistyped off-chain would produce a policy that blocks exactly what it was
     *      meant to permit — and the error would only surface as an approval refused in
     *      the middle of a demo.
     */
    function test_privySelectorsMatchTheContracts() public view {
        _assertSelector(
            "submit((uint64,uint64,uint64,uint64,uint32,bytes32,bytes32,bytes32,int32,int32,uint128,uint128),bytes,bytes[])",
            RebalanceVault.submit.selector
        );
        _assertSelector(
            "execute(bytes32,(address,address,uint128,uint128)[],bytes32)",
            RebalanceVault.execute.selector
        );
        _assertSelector("approve(bytes32)", RebalanceVault.approve.selector);
        _assertSelector(
            "queueCurrencyPolicy(address,(uint128,uint128,uint128,uint128,uint128,uint128))",
            TreasuryPolicy.queueCurrencyPolicy.selector
        );
        _assertSelector(
            "queueRiskParams((uint32,uint32,uint32,uint32,uint32,uint128))",
            TreasuryPolicy.queueRiskParams.selector
        );
        _assertSelector("commitBandParams(bytes32)", TreasuryPolicy.commitBandParams.selector);
    }

    function _assertSelector(string memory signature, bytes4 expected) internal view {
        string memory path = string.concat(".selectors.", '["', signature, '"].selector');
        // `parseJson` automatically converts a hex string into `bytes`: reading it as a
        // `string` made it unreadable. Ask for bytes directly.
        assertEq(bytes4(vm.parseJsonBytes(json, path)), expected, signature);
    }

    /// @dev The domain separator depends on the deployed address and therefore cannot
    ///      appear in a static fixture. Its construction is checked here; the value itself
    ///      is cross-checked against the engine by the end-to-end scenario.
    function test_domainSeparatorIsBuiltFromTheDeployedAddress() public view {
        bytes32 expected = keccak256(
            abi.encode(
                vm.parseJsonBytes32(json, ".domainTypeHash"),
                keccak256("NEAP"),
                keccak256("1"),
                block.chainid,
                address(verifier)
            )
        );
        assertEq(verifier.domainSeparator(), expected);
    }
}
